params:
    path: &path ${PROJECT_DIR}/logs/prod


handlers:

    regular_file_handler:
        filename: !joinPath [ *path, "regular.log" ]

    extended_file_handler:
        filename: !joinPath [ *path, "extended.log" ]

    error_file_handler:
        filename: !joinPath [ *path, "errors.log" ]

    warn_file_handler:
        filename: !joinPath [ *path, "warn.log" ]
